fix: avoid endless recursion
freeCodeCamp/demo-projects pull request #142
Opened 2022-01-31 20:49 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

In the current state, the recursion get stuck in a loop if an unsolvable puzzle string is submitted. @ojeytonwilliams and I discussed an approach to fixing this with an arbitrary timeout, but after further thought I decided counting the recursive calls might be better.

A quick Google search gave me the "world's hardest sudoku", which the solver took 49000+ recursive calls to solve. By counting and capping the recursive calls at 50000, this PR will add an assumption that additional calls mean the puzzle is unsolvable and back out of the recursion.

Passing an unsolvable string with this change no longer locks up the server, but instead properly displays "puzzle cannot be solved" in the front end.

2022-01-31 20:52 UTC, nhcarrigan commented on apps/sudoku-solver/controllers/sudoku-solver.js
> +    // Anything exceeding this should be an unsolvable puzzle.
I hate magic numbers, so documented the reason for 50000 in the comments.

2022-01-31 23:03 UTC, ojeytonwilliams requested changes
Errant log aside, LGTM

2022-01-31 23:03 UTC, ojeytonwilliams commented on apps/sudoku-solver/controllers/sudoku-solver.js
> +    console.log(this._recursions);
```suggestion
```

2022-02-01 04:49 UTC, nhcarrigan commented on apps/sudoku-solver/controllers/sudoku-solver.js
> +    console.log(this._recursions);
I knew I'd forget this.

2022-02-01 07:24 UTC, ojeytonwilliams approved these changes

2022-02-01 07:25 UTC, merged