New Personal Library Example
freeCodeCamp/demo-projects pull request #39
Opened 2020-11-10 22:46 UTC by nhcarrigan

Using the [new boilerplate](https://github.com/freeCodeCamp/boilerplate-project-library/pull/5), I have put together an example project which passes [the proposed /learn tests](https://github.com/freeCodeCamp/freeCodeCamp/pull/39642).

I left the styling untouched, and tried to keep the code similar to what a camper at this point in the curriculum should be able to read and understand.

I have a [Repl.it instance available](https://personal-library.nicholascarriga.repl.co/) for testing against the /learn PR.

/cc @SaintPeter @RandellDawson

2020-11-11 00:21 UTC, RandellDawson requested changes
The example project changes correctly passes all the `/learn` changes on the [corresponding learn PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/39642). 

Just have two change suggestions.

2020-11-11 00:21 UTC, RandellDawson commented on personal-library/routes/api.js
> +Mongoose.connect(MONGODB_CONNECTION_STRING, (err) => {
To handle the two deprecation warnings:
```suggestion
Mongoose.connect(MONGODB_CONNECTION_STRING,  { useNewUrlParser: true, useUnifiedTopology: true }, (err) => {
```

2020-11-11 00:30 UTC, nhcarrigan commented on personal-library/routes/api.js
> +Mongoose.connect(MONGODB_CONNECTION_STRING, (err) => {
Whoops! Meant to go back and add this.

2020-11-11 01:02 UTC, RandellDawson approved these changes

2020-11-11 01:04 UTC, RandellDawson commented
@nhcarrigan These changes look good to me know. Once this approve by another mod, we will still need to wait until the changes on the corresponding `/learn` PR have hit production before we can merge it.

Thanks for putting this together so quickly!

2020-11-11 01:04 UTC, nhcarrigan commented
Glad to help!

2020-11-12 22:15 UTC, moT01 approved these changes
LGTM 🎉 Should be good to go once the learn PR hits production 😄

2020-11-18 22:06 UTC, RandellDawson commented
The `/learn` changes have hit production, so I am merging this now.  I will restart the project in a few minutes.

2020-11-18 22:07 UTC, merged