fix: updates to required JS projects
freeCodeCamp/demo-projects pull request #520
Opened 2023-11-16 05:17 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to ...

2023-11-22 22:50 UTC, jdwilkin4 commented
Hey @scissorsneedfoodtoo ! 

I will have more time to review this later on this week.
But one thing I have noticed in these projects is that we are using `innerHTML` for everything when we really should reserve that for when we are setting new HTML. If we are just setting text, then we should use another method like `textContent`.

2023-11-23 07:16 UTC, scissorsneedfoodtoo commented
Hey @jdwilkin4, thanks for taking a quick look at this and catching the issue with using `innerHTML` rather than `innerText`. That's something I missed while originally reviewing these projects.

I can go in and fix those, and apply the updated code to the Learn PR solutions.

2023-11-27 00:03 UTC, jdwilkin4 requested changes
Looks good.
Left a couple of comments 👍

2023-11-27 11:57 UTC, scissorsneedfoodtoo commented on apps/pokemon-search-app/index.html
> +          <div class="sprite-container"><img alt id="sprite" /></div>
Thanks for taking a look at this, @jdwilkin4, and for running the code though a validator. That's a great idea – I've just been using Prettier this whole time, not checking for actual validation errors.

We did have a default image before with a Pikachu sprite, but it was decided that we should remove that just to be extra safe.

We could go with a black box there, just a `div` with a background color and swap it out for an `img` element whenever appropriate. Or we could just add an `img` there whenever we get a response from the API proxy and remove it whenever there are errors.

I'll play around with it and push an update ASAP.

2023-11-28 11:05 UTC, scissorsneedfoodtoo commented on apps/pokemon-search-app/index.html
> +          <div class="sprite-container"><img alt id="sprite" /></div>
This should be fixed in the demo here, and in the solution in the Learn PR.

2023-11-28 11:05 UTC, scissorsneedfoodtoo commented on apps/pokemon-search-app/public/script.js
> +  sprite.src = '';
This should be fixed in the demo here, and in the solution in the Learn PR.

2023-12-01 01:27 UTC, jdwilkin4 approved these changes
Looks good 👍

2023-12-11 18:04 UTC, naomi-lgbt reviewed
Couple of nits

2023-12-12 00:16 UTC, jdwilkin4 commented on apps/palindrome-checker/public/script.js
>      return;
I think @scissorsneedfoodtoo mentioned there was some sort of issue about having them strip the characters. 
There was a prior discussion thread in the old staff chat but I don't remember the exact reason why this was a problem.
So @scissorsneedfoodtoo should have the details on that.

2023-12-14 08:13 UTC, scissorsneedfoodtoo commented on apps/palindrome-checker/public/script.js
>      return;
The last messages in chat were about the demo project incorrectly flagging spaces as special characters. I can't remember exactly why we have this alert for special characters, or when it got added.

I'm in favor of updating the project so it's closer to the current palindrome checker, where special characters and spaces are stripped out before checking for a palindrome. It shouldn't be too difficult to update the solution here and add a couple of extra tests.

2023-12-15 10:12 UTC, scissorsneedfoodtoo commented on apps/roman-numeral-converter/index.html
Done! It didn't take all that long to swap some of the colors around. I'll post screenshots of the latest Roman Numeral Converter styling below so they're easier for everyone to see.

2023-12-15 10:32 UTC, scissorsneedfoodtoo commented
Here's what the dark mode version of the Roman Numeral Converter project looks like:

![image](https://github.com/freeCodeCamp/demo-projects/assets/2051070/bc12587d-23ee-42dd-99e8-ab863a4d1ee7)

![image](https://github.com/freeCodeCamp/demo-projects/assets/2051070/f3128445-9ab3-4477-97ca-fb0105867340)

2023-12-15 10:59 UTC, scissorsneedfoodtoo commented
Added a logo and adjusted the styling of the Pokémon Search app slightly:

![image](https://github.com/freeCodeCamp/demo-projects/assets/2051070/93d7de13-9438-4c49-8be3-6d80cc9c9e0a)

2023-12-15 11:00 UTC, scissorsneedfoodtoo commented on apps/palindrome-checker/public/script.js
>      return;
The Palindrome Check here and in https://github.com/freeCodeCamp/freeCodeCamp/pull/52370 have been updated so they're closer to the solution we have in the current JS certification where whitespace and special characters are stripped before checking for a palindrome.

2023-12-15 14:53 UTC, naomi-lgbt approved these changes
<img width="417" alt="image" src="https://github.com/freeCodeCamp/demo-projects/assets/63889819/ba492ffe-65ba-4c77-8a58-cc9edea97afe">

Okay, everything is looking good on my end. Let's go ahead and land this. Thanks for all your work on these!

2023-12-15 14:53 UTC, merged