fix: no negative currency cash register
freeCodeCamp/demo-projects pull request #564
Opened 2024-01-27 22:41 UTC by a2937

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #559

2024-02-06 19:36 UTC, gikf commented on apps/cash-register/public/script.js
>          result.change.push([reversedCid[i][0], count * denominations[i]]);
```suggestion
        result.change.push([reversedCid[i][0], (count * denominations[i]).toFixed(2)]);
```
Rounding for status didn't survive merge conflict :slightly_smiling_face:

2024-04-02 16:04 UTC, a2937 commented
I linted the file so this can finally be merged.

2024-04-02 17:19 UTC, naomi-lgbt requested changes
Unfortunately this introduces a regression - the final test no longer passes for the demo project with these changes (there's likely an off-by-one error going on somewhere).

It may be beneficial to refactor the project to handle all of the math with cents as the base instead of dollars.

2024-09-03 10:56 UTC, gikf commented
Hey @a2937

Thank you for opening this pull request.

As there was different PR - #602 - addressing linked issue merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

2024-09-03 10:56 UTC, closed without merging